#!/usr/bin/env bash
set -e

docker build -t aggregail/mongodb/admin .
#docker container rm amdb_admin

docker tag aggregail/mongodb/admin aggregail/mongodb-admin
docker push aggregail/mongodb-admin
#docker run -p 5000:80 -p 5001:443 \
#  --name amdb_admin \
#  --network=aggregailmongodb_default \
#  --env-file docker.env \
#  aggregail/mongodb/admin
