version: '3'
services:
  mongodb:
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ADVERTISED_HOSTNAME: $MONGODB_PRIMARY_HOST
      MONGODB_PORT_NUMBER: 27017
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: $MONGODB_REPLICA_SET_KEY
      MONGODB_REPLICA_SET_NAME: $MONGODB_REPLICA_SET_NAME
      MONGODB_ROOT_USERNAME: $MONGODB_ROOT_USERNAME
      MONGODB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
  
  aggregail-mongodb-admin:
    image: aggregail/mongodb-admin
    restart: always
    ports:
      - 5000:80
    environment:
      ASPNETCORE_Environment: $ASPNETCORE_Environment
      ASPNETCORE_Urls: $ASPNETCORE_Urls
      AGGREGAIL_ConnectionString: $AGGREGAIL_ConnectionString
      AGGREGAIL_Database: $AGGREGAIL_Database
      AGGREGAIL_Users_Collection: $AGGREGAIL_Users_Collection
