#!/usr/bin/env bash
set -e

dotnet publish -r osx-x64 -c Release --self-contained true -p:PublishSingleFile=true
dotnet publish -r linux-x64 -c Release --self-contained true -p:PublishSingleFile=true
dotnet publish -r win-x64 -c Release --self-contained true -p:PublishSingleFile=true